### ISSUE TITLE
Allow the mock service to be initially configured with preloaded endpoints mocked

### ISSUE THREAD

**Issue by wchan2** [wchan2/mock_service#5]
As a user of the library, I would like to be able to create a mock service that can have endpoints preloaded in addition to registering mock endpoints via HTTP requests.

**Comment by enriqueChen** [comment]
add pull request for this issue: https://github.com/wchan2/mock_service/pull/6/files

**Comment by wchan2** [comment]
If you link the pull request with the issue, the issue can be closed with the pull request as referenced [here](https://github.com/blog/1506-closing-issues-via-pull-requests) 😄 .
